const menuLangData = {
    "pt": {
        "menuTitle": "Especialidades do Dia",
        "dailyMenuTitle": "Menu Semanal de Almoço",
        "dailyMenuSubtitleToday": "Destaque de Hoje:",
        "dailyMenuWeekend": "Fim-de-semana: Hoje não há Menu Especial. Consulte o Menu À La Carte.",
        "aLaCarteButtonOpen": "Ocultar Menu",
        "aLaCarteButtonClosed": "Ver Menu Completo",
        "alacarteTitle": "Menu À La Carte",
        "petiscosTitle": "Petiscos",
        "sopasTitle": "Sopas",
        "snacksTitle": "Snacks",
        "dessertsTitle": "Sobremesas",
        "petisco1Title": "Rabada",
        "petisco1Desc": "",
        "petisco1Price": "350 MT",
        "petisco2Title": "Amêijoas a Nyumba",
        "petisco2Desc": "",
        "petisco2Price": "400 MT",
        "petisco3Title": "Cabeça de Salmão",
        "petisco3Desc": "",
        "petisco3Price": "350 MT",
        "petisco4Title": "Camarão Alhinho",
        "petisco4Desc": "",
        "petisco4Price": "350 MT",
        "petisco5Title": "Chouriço (c/ Batata e Salada)",
        "petisco5Desc": "",
        "petisco5Price": "400 MT",
        "petisco6Title": "Tábua de 7 Queijos e Broa",
        "petisco6Desc": "",
        "petisco6Price": "750 MT",
        "petisco7Title": "Dobradinha",
        "petisco7Desc": "",
        "petisco7Price": "350 MT",
        "sopa1Title": "Creme de Cenoura",
        "sopa1Desc": "",
        "sopa1Price": "150 MT",
        "sopa2Title": "Creme de Abóbora",
        "sopa2Desc": "",
        "sopa2Price": "180 MT",
        "sopa3Title": "Sopa de Mandioca",
        "sopa3Desc": "",
        "sopa3Price": "150 MT",
        "sopa4Title": "Caldo Verde",
        "sopa4Desc": "",
        "sopa4Price": "180 MT",
        "sopa5Title": "Sopa de Feijão",
        "sopa5Desc": "",
        "sopa5Price": "150 MT",
        "sopa6Title": "Sopa de Legumes",
        "sopa6Desc": "",
        "sopa6Price": "150 MT",
        "snack1Title": "Salgados (4)",
        "snack1Desc": "",
        "snack1Price": "250 MT",
        "snack2Title": "Hamburguer Simples (c/ Ovo ou Queijo e Batata)",
        "snack2Desc": "",
        "snack2Price": "250 MT",
        "snack3Title": "Hamburguer Completo",
        "snack3Desc": "Com queijo, ovo, alface, queijo cheddar, maionese caseira, alface, cebola caramelizada e batata frita",
        "snack3Price": "350 MT",
        "snack4Title": "Nyumba Burguer",
        "snack4Desc": "Com maionese caseira, fiambre ou bacon, queijo mozzarella, batatas fritas, cebola caramelizada, picles, rúcula",
        "snack4Price": "500 MT",
        "snack5Title": "Hamburguer de Alheira",
        "snack5Desc": "Com ovo, rúcula, queijo mozzarella e batata frita",
        "snack5Price": "600 MT",
        "snack6Title": "Hamburguer de Frango",
        "snack6Desc": "Com ovo, queijo mozzarella, alface e batata",
        "snack6Price": "350 MT",
        "snack7Title": "Prego no Pão",
        "snack7Desc": "",
        "snack7Price": "350 MT",
        "snack8Title": "Cachorro quente (c/ Batatas)",
        "snack8Desc": "",
        "snack8Price": "350 MT",
        "snack9Title": "Tosta Mista",
        "snack9Desc": "",
        "snack9Price": "280 MT",
        "snack10Title": "Tosta de Atum",
        "snack10Desc": "",
        "snack10Price": "350 MT",
        "snack11Title": "Tosta de Caranguejo",
        "snack11Desc": "",
        "snack11Price": "450 MT",
        "snack12Title": "Tosta de Frango",
        "snack12Desc": "",
        "snack12Price": "350 MT",
        "snack13Title": "Matabicho Thafo",
        "snack13Desc": "Com 2 ovos, tomate, salsichas, torradas, feijão doce, bacon",
        "snack13Price": "450 MT",
        "dessert1Title": "Sorvete",
        "dessert1Desc": "",
        "dessert1Price": "150 MT",
        "dessert2Title": "Salada de Fruta",
        "dessert2Desc": "",
        "dessert2Price": "180 MT",
        "dessert3Title": "Pudim",
        "dessert3Desc": "",
        "dessert3Price": "150 MT",
        "dessert4Title": "Bolo de Chocolate",
        "dessert4Desc": "",
        "dessert4Price": "200 MT",
        "dessert5Title": "Doce de Mandioca",
        "dessert5Desc": "",
        "dessert5Price": "150 MT",
        "dessert6Title": "Arroz Doce",
        "dessert6Desc": "",
        "dessert6Price": "150 MT",
        "dayNames": {
            "0": "Domingo",
            "1": "2ª Feira",
            "2": "3ª Feira",
            "3": "4ª Feira",
            "4": "5ª Feira",
            "5": "6ª Feira",
            "6": "Sábado"
        }
    },
    "en": {
        "menuTitle": "Daily Specials",
        "dailyMenuTitle": "Weekly Lunch Menu",
        "dailyMenuSubtitleToday": "Today's Highlight:",
        "dailyMenuWeekend": "Weekend: No special menu today. Please check the À La Carte Menu.",
        "aLaCarteButtonOpen": "Hide Menu",
        "aLaCarteButtonClosed": "View Full Menu",
        "alacarteTitle": "À La Carte Menu",
        "petiscosTitle": "Appetizers",
        "sopasTitle": "Soups",
        "snacksTitle": "Snacks",
        "dessertsTitle": "Desserts",
        "petisco1Title": "Oxtail",
        "petisco1Desc": "",
        "petisco1Price": "350 MT",
        "petisco2Title": "Clams Nyumba Style",
        "petisco2Desc": "",
        "petisco2Price": "400 MT",
        "petisco3Title": "Salmon Head",
        "petisco3Desc": "",
        "petisco3Price": "350 MT",
        "petisco4Title": "Garlic Prawns",
        "petisco4Desc": "",
        "petisco4Price": "350 MT",
        "petisco5Title": "Chouriço (with Potato and Salad)",
        "petisco5Desc": "",
        "petisco5Price": "400 MT",
        "petisco6Title": "Platter of 7 Cheeses and Cornbread",
        "petisco6Desc": "",
        "petisco6Price": "750 MT",
        "petisco7Title": "Tripe Stew",
        "petisco7Desc": "",
        "petisco7Price": "350 MT",
        "sopa1Title": "Carrot Cream Soup",
        "sopa1Desc": "",
        "sopa1Price": "150 MT",
        "sopa2Title": "Pumpkin Cream Soup",
        "sopa2Desc": "",
        "sopa2Price": "180 MT",
        "sopa3Title": "Cassava Soup",
        "sopa3Desc": "",
        "sopa3Price": "150 MT",
        "sopa4Title": "Portuguese Kale Soup",
        "sopa4Desc": "",
        "sopa4Price": "180 MT",
        "sopa5Title": "Bean Soup",
        "sopa5Desc": "",
        "sopa5Price": "150 MT",
        "sopa6Title": "Vegetable Soup",
        "sopa6Desc": "",
        "sopa6Price": "150 MT",
        "snack1Title": "Savory Pastries (4)",
        "snack1Desc": "",
        "snack1Price": "250 MT",
        "snack2Title": "Simple Burger (with Egg or Cheese and Potato)",
        "snack2Desc": "",
        "snack2Price": "250 MT",
        "snack3Title": "Complete Burger",
        "snack3Desc": "With cheese, egg, lettuce, cheddar cheese, homemade mayonnaise, lettuce, caramelized onion and fries",
        "snack3Price": "350 MT",
        "snack4Title": "Nyumba Burger",
        "snack4Desc": "With homemade mayonnaise, ham or bacon, mozzarella cheese, fries, caramelized onion, pickles, arugula",
        "snack4Price": "500 MT",
        "snack5Title": "Alheira Sausage Burger",
        "snack5Desc": "With egg, arugula, mozzarella cheese and fries",
        "snack5Price": "600 MT",
        "snack6Title": "Chicken Burger",
        "snack6Desc": "With egg, mozzarella cheese, lettuce and potato",
        "snack6Price": "350 MT",
        "snack7Title": "Steak Sandwich",
        "snack7Desc": "",
        "snack7Price": "350 MT",
        "snack8Title": "Hot Dog (with Potatoes)",
        "snack8Desc": "",
        "snack8Price": "350 MT",
        "snack9Title": "Grilled Ham and Cheese Sandwich",
        "snack9Desc": "",
        "snack9Price": "280 MT",
        "snack10Title": "Tuna Melt",
        "snack10Desc": "",
        "snack10Price": "350 MT",
        "snack11Title": "Crab Melt",
        "snack11Desc": "",
        "snack11Price": "450 MT",
        "snack12Title": "Chicken Melt",
        "snack12Desc": "",
        "snack12Price": "350 MT",
        "snack13Title": "Thafo Breakfast",
        "snack13Desc": "With 2 eggs, tomato, sausages, toast, baked beans, bacon",
        "snack13Price": "450 MT",
        "dessert1Title": "Ice Cream",
        "dessert1Desc": "",
        "dessert1Price": "150 MT",
        "dessert2Title": "Fruit Salad",
        "dessert2Desc": "",
        "dessert2Price": "180 MT",
        "dessert3Title": "Pudding",
        "dessert3Desc": "",
        "dessert3Price": "150 MT",
        "dessert4Title": "Chocolate Cake",
        "dessert4Desc": "",
        "dessert4Price": "200 MT",
        "dessert5Title": "Cassava Sweet",
        "dessert5Desc": "",
        "dessert5Price": "150 MT",
        "dessert6Title": "Rice Pudding",
        "dessert6Desc": "",
        "dessert6Price": "150 MT",
        "dayNames": {
            "0": "Sunday",
            "1": "Monday",
            "2": "Tuesday",
            "3": "Wednesday",
            "4": "Thursday",
            "5": "Friday",
            "6": "Saturday"
        }
    }
};